### ISSUE TITLE
    data_loader_train = DataLoader(d_train, batch_size=batch_size, shuffle=True, collate_fn=collate) NameError: name 'collate' is not defined

### ISSUE THREAD

**Issue by Faker0715** [zixun-lan/AEDNet-Adaptive-Edge-Deleting-Network-For-Subgraph-Matching#1]
data_loader_train = DataLoader(d_train, batch_size=batch_size, shuffle=True, collate_fn=collate)
NameError: name 'collate' is not defined

**Comment by zixun-lan** [comment]
maybe lacking 'from dataSet import collate'.
