### ISSUE TITLE
关于评价指标f1score

### ISSUE THREAD

**Issue by gouliang1997** [zixun-lan/AEDNet-Adaptive-Edge-Deleting-Network-For-Subgraph-Matching#2]
代码和论文里说的是F1-Score，但是utils里的metric_f1函数计算的是top-1 accuarcy，并不是F1-Score的计算吧（如果我理解有误的话请指正

**Comment by zixun-lan** [comment]
当寻找 predicted matrix每行最大值作为查询图相应node的匹配节点时，找出的top1子图和ground-truth子图大小一致。且一个ground-truth子图与data graph 的 ground-truth matching matrix矩阵每行有且只有一个1。
此时P=TP/(TP+FP)=R= TP/(TP+FN)。
由于 F1 = 2*P*R/(P+R)，当P=R时，F1=2*P*P/(P+P)= (2*P^2)/(2*P) = P.

**Comment by gouliang1997** [comment]
可是按照creatData.py里的方法生成的ground-truth matching matrix每行不只有一个1

**Comment by zixun-lan** [comment]
在creatData.py有两个方法，一个不限制唯一子图，一个限制生成唯一子图。无论哪一个，评估时都只需要拿出解中的任意一个子图评估j就可以，因为解中任意的子图也是GT。5.4节对评估标准做出了定义。
